# yaml-language-server: $schema=https://raw.githubusercontent.com/cangulo-actions/semver/0.13.0/config.schema.yml

versioning:
  file: package.json

commits:
  - type: break
    release: major
  - type: feat
    release: minor
  - type: fix
    release: patch
  - type: refactor
    release: none
  - type: docs
    release: none
  - type: ci
    release: none

pre-commit:
  commands:
    - npm install
    - npm run build
