name: 🚀 continuous-delivery

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  semver:
    name: 🚀 release new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CANGULO_BOT_PUSH_COMMITS }} # required for pushing to main, it is a protected branch

      - name: release new version
        uses: cangulo-actions/semver@issue109
        id: semver
        with:
          configuration: commits-semver.yml
          create-gh-release: true
          print-summary: true
          print-annotations: true
          include-previous-non-releasable-commits: true

      # - name: add package-lock.json to git changes
      #   run: git add package-lock.json

      # - name: push zip file to GH release
      #   run: |
      #     gh release upload <tag> <files>
