name: 🚀 continuous-delivery

on:
  push:
    branches:
      - main

jobs:
  semver:
    name: 🚀 release new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CANGULO_BOT_PUSH_COMMITS }} # required for pushing to main, it is a protected branch

      - name: release new version
        uses: cangulo-actions/semver@0.11.1
        id: semver
        with:
          configuration: commits-semver.yml
          create-gh-release: true
          print-summary: true
          print-annotations: true
          include-previous-non-releasable-commits: true
