name: 🚀 continuous-delivery

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  semver:
    name: 🚀 release new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CANGULO_BOT_PUSH_COMMITS }} # required for pushing to main, it is a protected branch

      - name: release new version
        uses: cangulo-actions/semver@0.14.2
        id: semver
        with:
          configuration: .github/semver.yml
          create-gh-release: true
          print-summary: true
          print-annotations: true
          include-previous-non-releasable-commits: true

      - name: push zip file to GH release
        if: ${{ steps.semver.outputs.new-version-released == 'true' }}
        env:
          NEW_VERSION: ${{ steps.semver.outputs.version }}
          ASSET_FILE: "cangulo-blog-components-${{ steps.semver.outputs.version }}.tgz"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm pack
          gh release upload $NEW_VERSION $ASSET_FILE

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        if: ${{ steps.semver.outputs.new-version-released == 'true' }}
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: publish to NPM
        if: ${{ steps.semver.outputs.new-version-released == 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_CANGULO_BLOG_COMPONENTS }}
          ASSET_FILE: "cangulo-blog-components-${{ steps.semver.outputs.version }}.tgz"
        run: |
          npm publish --access=public
